1st commit
yarustam/7th-sprint-Yandex pull request #1
Opened 2024-04-17 15:58 UTC by yarustam

2024-04-17 20:51 UTC, dirtymew requested changes
Привет Рустам

Хорошая работа - api описано верно

есть что поправить см PR

2024-04-17 20:51 UTC, dirtymew commented on precode.go
> +func postTask(w http.ResponseWriter, r *http.Request) {
предлагаю переименовать в createTask

2024-04-17 20:51 UTC, dirtymew commented on precode.go
> +		http.Error(w, err.Error(), http.StatusInternalServerError)
тут по заданию другая ошибка должны быть 400 Bad Request

2024-04-17 20:51 UTC, dirtymew commented on precode.go
> +	tasks[task.ID] = task
Код не только добавляет но и обновляет задачу - обычно создание и обновление - это разные энпоинты.

Вообще в задание явно не описано, но судя по коду ответа 201   - должно быть только создание элемента

Eще хорошо бы валидировать то что приходит из вне,  можно значения полей например:
 - если нет id то генерировать -
 -  если нет applications то добавить из запроса user agent https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent

2024-04-17 20:51 UTC, dirtymew commented on precode.go
> +func getTaskOnID(w http.ResponseWritte, r *http.Request) {
getTask

2024-04-17 20:51 UTC, dirtymew commented on precode.go
> +func taskDelete(w http.ResponseWriter, r *http.Request) {
deleteTask

2024-04-18 17:23 UTC, yarustam commented on precode.go
> +	tasks[task.ID] = task
не понял, что от меня нужно?

2024-04-18 23:02 UTC, dirtymew requested changes
Привет Рустам

осталось немного подправить эндпоинт по созданию задачи

2024-04-18 23:02 UTC, dirtymew commented on precode.go
> +	tasks[task.ID] = task
нужно исправить код так что бы при получении запроса на создание задачи с существующим id задача не обновлялась - как сейчас  а возвращается ошибка

2024-04-20 11:48 UTC, dirtymew approved these changes
Привет Рустам

критические замечания устранил - зачет

2024-04-20 11:48 UTC, dirtymew commented on precode.go
> +		http.Error(w, "Task with this ID already exist.", http.StatusConflict)
тут только код не тот - см задание 
но возвращать не буду

2024-04-20 12:49 UTC, yarustam commented on precode.go
> +		http.Error(w, "Task with this ID already exist.", http.StatusConflict)
надо 400 BadRequest?

2024-04-23 11:29 UTC, merged